services:
  - type: web
    name: bank-saving-system-api
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
